/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuprimentosRouteImport } from './routes/suprimentos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as ProcessamentoRouteImport } from './routes/processamento'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FichasRouteImport } from './routes/fichas'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DreRouteImport } from './routes/dre'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as CentralRouteImport } from './routes/central'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AuditoriasRouteImport } from './routes/auditorias'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalLocationIdRouteImport } from './routes/local.$locationId'
import { Route as InventarioLocationIdRouteImport } from './routes/inventario.$locationId'

const SuprimentosRoute = SuprimentosRouteImport.update({
  id: '/suprimentos',
  path: '/suprimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessamentoRoute = ProcessamentoRouteImport.update({
  id: '/processamento',
  path: '/processamento',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasRoute = FichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriasRoute = AuditoriasRouteImport.update({
  id: '/auditorias',
  path: '/auditorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalLocationIdRoute = LocalLocationIdRouteImport.update({
  id: '/local/$locationId',
  path: '/local/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioLocationIdRoute = InventarioLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => InventarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auditorias': typeof AuditoriasRoute
  '/categorias': typeof CategoriasRoute
  '/central': typeof CentralRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/equipe': typeof EquipeRoute
  '/fichas': typeof FichasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/processamento': typeof ProcessamentoRoute
  '/producao': typeof ProducaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suprimentos': typeof SuprimentosRoute
  '/inventario/$locationId': typeof InventarioLocationIdRoute
  '/local/$locationId': typeof LocalLocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auditorias': typeof AuditoriasRoute
  '/categorias': typeof CategoriasRoute
  '/central': typeof CentralRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/equipe': typeof EquipeRoute
  '/fichas': typeof FichasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/processamento': typeof ProcessamentoRoute
  '/producao': typeof ProducaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suprimentos': typeof SuprimentosRoute
  '/inventario/$locationId': typeof InventarioLocationIdRoute
  '/local/$locationId': typeof LocalLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auditorias': typeof AuditoriasRoute
  '/categorias': typeof CategoriasRoute
  '/central': typeof CentralRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dre': typeof DreRoute
  '/equipe': typeof EquipeRoute
  '/fichas': typeof FichasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/processamento': typeof ProcessamentoRoute
  '/producao': typeof ProducaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/suprimentos': typeof SuprimentosRoute
  '/inventario/$locationId': typeof InventarioLocationIdRoute
  '/local/$locationId': typeof LocalLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/auditorias'
    | '/categorias'
    | '/central'
    | '/checklists'
    | '/configuracoes'
    | '/dre'
    | '/equipe'
    | '/fichas'
    | '/fornecedores'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/notas'
    | '/processamento'
    | '/producao'
    | '/relatorios'
    | '/reset-password'
    | '/signup'
    | '/suprimentos'
    | '/inventario/$locationId'
    | '/local/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/auditorias'
    | '/categorias'
    | '/central'
    | '/checklists'
    | '/configuracoes'
    | '/dre'
    | '/equipe'
    | '/fichas'
    | '/fornecedores'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/notas'
    | '/processamento'
    | '/producao'
    | '/relatorios'
    | '/reset-password'
    | '/signup'
    | '/suprimentos'
    | '/inventario/$locationId'
    | '/local/$locationId'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/auditorias'
    | '/categorias'
    | '/central'
    | '/checklists'
    | '/configuracoes'
    | '/dre'
    | '/equipe'
    | '/fichas'
    | '/fornecedores'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/notas'
    | '/processamento'
    | '/producao'
    | '/relatorios'
    | '/reset-password'
    | '/signup'
    | '/suprimentos'
    | '/inventario/$locationId'
    | '/local/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AuditoriasRoute: typeof AuditoriasRoute
  CategoriasRoute: typeof CategoriasRoute
  CentralRoute: typeof CentralRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DreRoute: typeof DreRoute
  EquipeRoute: typeof EquipeRoute
  FichasRoute: typeof FichasRoute
  FornecedoresRoute: typeof FornecedoresRoute
  HistoricoRoute: typeof HistoricoRoute
  InventarioRoute: typeof InventarioRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotasRoute: typeof NotasRoute
  ProcessamentoRoute: typeof ProcessamentoRoute
  ProducaoRoute: typeof ProducaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuprimentosRoute: typeof SuprimentosRoute
  LocalLocationIdRoute: typeof LocalLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suprimentos': {
      id: '/suprimentos'
      path: '/suprimentos'
      fullPath: '/suprimentos'
      preLoaderRoute: typeof SuprimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processamento': {
      id: '/processamento'
      path: '/processamento'
      fullPath: '/processamento'
      preLoaderRoute: typeof ProcessamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas': {
      id: '/fichas'
      path: '/fichas'
      fullPath: '/fichas'
      preLoaderRoute: typeof FichasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditorias': {
      id: '/auditorias'
      path: '/auditorias'
      fullPath: '/auditorias'
      preLoaderRoute: typeof AuditoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$locationId': {
      id: '/local/$locationId'
      path: '/local/$locationId'
      fullPath: '/local/$locationId'
      preLoaderRoute: typeof LocalLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/$locationId': {
      id: '/inventario/$locationId'
      path: '/$locationId'
      fullPath: '/inventario/$locationId'
      preLoaderRoute: typeof InventarioLocationIdRouteImport
      parentRoute: typeof InventarioRoute
    }
  }
}

interface InventarioRouteChildren {
  InventarioLocationIdRoute: typeof InventarioLocationIdRoute
}

const InventarioRouteChildren: InventarioRouteChildren = {
  InventarioLocationIdRoute: InventarioLocationIdRoute,
}

const InventarioRouteWithChildren = InventarioRoute._addFileChildren(
  InventarioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AuditoriasRoute: AuditoriasRoute,
  CategoriasRoute: CategoriasRoute,
  CentralRoute: CentralRoute,
  ChecklistsRoute: ChecklistsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DreRoute: DreRoute,
  EquipeRoute: EquipeRoute,
  FichasRoute: FichasRoute,
  FornecedoresRoute: FornecedoresRoute,
  HistoricoRoute: HistoricoRoute,
  InventarioRoute: InventarioRouteWithChildren,
  LoginRoute: LoginRoute,
  NotasRoute: NotasRoute,
  ProcessamentoRoute: ProcessamentoRoute,
  ProducaoRoute: ProducaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuprimentosRoute: SuprimentosRoute,
  LocalLocationIdRoute: LocalLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
